## 神经网络编程基础

### 1.二分分类

计算机保存图片的方式：
![010](images/010.png)

使用一个向量表示就是64*64*3维的特征。输入的特征向量的维度。

训练模型常用的符号：

![011](images/011.png)


### 2.logistic回归

logistic回归的思路：

![012](images/012.png)


w和b是待求的参数，是$x^n+1$维。

logistic回归的损失函数：

会定义一个不同的损失函数，它起着与误差平方相似的作用。

![013](images/013.png)

***成本函数等于个样本误差（损失函数）的求和取均值：***

![014](images/014.png)


### 使用梯度下降算法（精华）

![015](images/015.png)

成本函数是凸函数，利用凸优化进行最小值的求解。

![016](images/016.png)

梯度下降算法的详细讲解。


在logistic回归中使用梯度下降算法：

![019](images/019.png)


**对logistic回归的成本函数的解释：**

![027](images/027.png)

![028](images/028.png)

logist回归的成本函数是根据参数最大化样本的概率（最大似然法，样本是独立同分布的），其中由于我们是最小化成本函数，所以我们不直接使用最大似然估计。

如上图，通过改变$w_1,w_2,b$的值，最小化损失函数——我们的目标。

![020](images/020.png)


上述是针对单样本的梯度下降，下面介绍应用到全部数据集的方法：

![021](images/021.png)

上述方法使用了多个for 循环，不适合在大数据集上使用，下面介绍一种向量化技术减缓这种for循环的使用，提高效率：

!
向量化是消除for循环的工具；

什么是向量化？

![022](images/022.png)

尽量减少for循环的使用，对使用向量化计算，提高数据处理的并行性。

## 向量化实现logistic回归：

![024](images/024.png)

![025](images/025.png)


**注意：根据梯度进行更新$w,b$的值**


### 导数

常用的求导函数等。


### 计算图

![017](images/017.png)

反向传播的链式法则

![018](images/018.png)



In [3]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print("向量化时间：",(toc-tic)*1000,"ms")
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print("循环时间为：",(toc-tic)*1000,"ms")


向量化时间： 1.0058879852294922 ms
循环时间为： 669.6105003356934 ms


## 广播（python）：


广播是将较小的矩阵“广播”到较大矩阵相同的形状尺度上，使它们对等以可以进行数学计算。注意的是较小的矩阵要是较大矩阵的倍数，否则无法使用广播。 

案例：

![026](images/026.png)

计算四种食物中，来自碳水化合物，蛋白质和脂肪的百分比各占多少？




In [18]:
import numpy as np

A=np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

print(A)

cal=A.sum(axis=0)   #axis=0表示操作列，axis=1表示操作行

percentage=100*A/cal.reshape(1,4)

print(percentage)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [20]:
#向量加数字  1
a=np.array([1,2,3,4])   #广播的例子   
b=100
c=a+b
print(c)

#矩阵加向量  2
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([100,200,300])

c1=a1+b1
print(c1)

[101 102 103 104]
[[101 202 303]
 [104 205 306]]


python中的一些规则：

+ 如果有一个（m,n）的矩阵，加减乘除一个(1,n)的矩阵，python会默认扩展（1，n）成为(m,n),然后对应项操作，(m,1)矩阵同理；

+ 如果一个(m,1)的矩阵，加减乘除一个实数，同上进行扩展。
